### ISSUE TITLE
Add support for linux

### ISSUE THREAD

**Issue by Eorclus** [Sombian/waifu-material-public#1]

**Comment by Sombian** [comment]
!! 리눅스 사용자 분은 없을거라 생각해서 컴파일을 안해왔습니다만,
지금 작업중인 부분 완성되면 darwin, windows, linux 전부 컴파일 해서 올려보도록 하겠습니다.
^^7

**Comment by Eorclus** [comment]
you can provide the source and build instruction if you want. I think linux user don't mind to compile it themself.

**Comment by Sombian** [comment]
> you can provide the source and build instruction if you want. I think linux user don't mind to compile it themself.

at the moment, i'm not planning to provide any source code.
thanks for your understanding.

**Comment by Sombian** [comment]
@Eorclus https://github.com/Sombian/waifu-material-public/releases/tag/2020-5-20

not sure will it work as theres not an way i could test this myself on else os
but here ya go.

**Comment by Sombian** [comment]
please reply within next 24 hours whether linux build works or not.
till then ill temporarily close this issue.

**Comment by Sombian** [comment]
thread will be locked permanently, please file an another issue to reach your concern.
thanks for your understanding.
